In [3]:
import tensorflow as tf 
import tensorflow_datasets as tfds
import math 
import numpy as np 
import matplotlib.pyplot as plt
import logging 
import cv2 as cv

datasets, metadata = tfds.load('fashion_mnist', as_supervised=True, with_info=True) # Loads the data
train_dataset, test_dataset = datasets['train'], datasets['test'] # Splits the dataset  

class_name = metadata.features['label'].names # Prints the names of the labels
print(class_name)
print(metadata.features) # Prints the features


num_train_examples = metadata.splits['train'].num_examples
num_test_examples = metadata.splits['test'].num_examples
print("Number of training examples: {}".format(num_train_examples))
print("Number of test examples:     {}".format(num_test_examples))

# for image, label in test_dataset.take(1): # this example is to check out one of the examples
#   break
# image = image.numpy().reshape((28,28))

# plt.figure()
# plt.imshow(image, cmap=plt.cm.binary)
# plt.colorbar()
# plt.grid(False)
# plt.show() # to check out one of the example shirts

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28, 1)), #flattens the 3d image into one array of numbers
    tf.keras.layers.Dense(512, activation=tf.nn.relu), #creates 128 level of neural networks
    tf.keras.layers.Dense(512, activation=tf.nn.relu),
    tf.keras.layers.Dense(512, activation=tf.nn.relu),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax) #softmax produces probability distribution 
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=['accuracy']) 

BATCH_SIZE = 32 #Batch size is the number of iterations the neural network does before it is updated 
train_dataset = train_dataset.cache().repeat().shuffle(num_train_examples).batch(BATCH_SIZE) #Updates dataset with batch included
test_dataset = test_dataset.cache().batch(BATCH_SIZE) 

model.fit(train_dataset, epochs=10, steps_per_epoch=math.ceil(num_test_examples/32)) # This trains the model 

test_loss, test_accuracy = model.evaluate(test_dataset, steps=math.ceil(num_test_examples/32))
print('Accuracy on test dataset:', test_accuracy)
print('Loss: ', test_loss)

for test_images, test_labels in test_dataset.take(1): #predict one sample from the data
  test_images = test_images.numpy()
  test_labels = test_labels.numpy()
  predictions = model.predict(test_images)

c:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']
FeaturesDict({
    'image': Image(shape=(28, 28, 1), dtype=uint8),
    'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
})
Number of training examples: 60000
Number of test examples:     10000
Epoch 1/10
313/313 [==============================] - 7s 14ms/step - loss: 4.8805 - accuracy: 0.6964
Epoch 2/10
313/313 [==============================] - 4s 14ms/step - loss: 0.7701 - accuracy: 0.7641
Epoch 3/10
313/313 [==============================] - 4s 14ms/step - loss: 0.6410 - accuracy: 0.7906
Epoch 4/10
313/313 [==============================] - 5s 15ms/step - loss: 0.5533 - accuracy: 0.8106
Epoch 5/10
313/313 [==============================] - 5s 15ms/step - loss: 0.5369 - accuracy: 0.8161
Epoch 6/10
313/313 [==============================] - 4s 14ms/step - loss: 0.5397 - accuracy: 0.8113
Epoch 7/10
313/313 [==============================] - 5s 15ms/step - loss: 0.4853 -

In [5]:
model.save_weights('./model_weights/data')



In [11]:
img = cv.imread("523.jpg", cv.IMREAD_GRAYSCALE)
print(img)

np_img = np.asanyarray(img)
print(np_img)



[[151 149 145 ... 161 163 164]
 [148 148 148 ... 161 162 165]
 [146 146 149 ... 161 163 166]
 ...
 [ 66  65  64 ...  97  83  85]
 [ 66  65  64 ...  91  80  85]
 [ 66  66  65 ...  99  89  86]]
[[151 149 145 ... 161 163 164]
 [148 148 148 ... 161 162 165]
 [146 146 149 ... 161 163 166]
 ...
 [ 66  65  64 ...  97  83  85]
 [ 66  65  64 ...  91  80  85]
 [ 66  66  65 ...  99  89  86]]


In [16]:
predictions = model.predict([np_img[:783]])
np.argmax(predictions[0])

ValueError: in user code:

    File "c:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "c:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "c:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 2111, in predict_step
        return self(x, training=False)
    File "c:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 28, 28, 1), found shape=(32, 640)
